sudo: required
git:
  depth: 1
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
services:
  - docker
script:
  - gradle check
  - gradle codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
